### ISSUE TITLE
need to add version pins to google-cloud-bigquery recipe

### ISSUE THREAD

**Issue by tswast** [conda-forge/google-cloud-bigquery-feedstock#54]
I notice that when I install `google-cloud-bigquery==1.28.0`, I also get `google-cloud-bigquery-storage==2.1.0`, which is incompatible.

We've set run-constrained dependencies:

https://github.com/conda-forge/google-cloud-bigquery-feedstock/blob/e9d3032ebea6cfcb6b38952795121b3d8c82921f/recipe/meta.yaml#L116-L122

But I suspect the run dependencies are overriding them:

https://github.com/conda-forge/google-cloud-bigquery-feedstock/blob/e9d3032ebea6cfcb6b38952795121b3d8c82921f/recipe/meta.yaml#L40-L47

**Comment by parthea** [comment]
Hi @tswast ,

It appears this was added in #55 . Ok to close?

**Comment by tswast** [comment]
@parthea Maybe? The PR bot gets confused by the way I did it. I have to manually delete some duplicate variables every time it sends a PR. I'll file another issue for that.

**Comment by tswast** [comment]
I think the correct way to do this is to have `google-cloud-bigquery` depend on `google-cloud-bigquery-core` with pin_subpackage, exact=True https://docs.conda.io/projects/conda-build/en/latest/resources/variants.html#referencing-subpackages

**Comment by xylar** [comment]
@tswast, I agree.  I think I've addressed this in #113
